### ISSUE TITLE
Multiuser Support

### ISSUE THREAD

**Issue by stefangries** [dckiller51/bodymiscale#11]
Hello! Thank you for your work on the integration, it is great.

I have a suggestion how to improve the integration even more. This is about multiuser support. For example, the users could be distinguished by the measured weight.

You could configure it like this for example:

```
bodymiscale:
  model_miscale: "181B"
  sensors:
    weight: sensor.weight_aurelien
    impedance: sensor.impedance_aurelien
  users:
    - name: "Username 1"
      height: 176
      born: "1990-04-10"
      gender: "male"
      weight_low: 70
      weight_heigh: 100
    - name: "Username 2"
      height: 170
      born: "1990-01-12"
      gender: "female"
      weight_low: 0
      weight_heigh: 70
```

Each user would then get his own entity. For this to be possible, the values would probably also have to be persisted in core.restore_state.
