### ISSUE TITLE
unknown sensor values, until scale woken up

### ISSUE THREAD

**Issue by yeaaaaaahh** [dckiller51/bodymiscale#147]
I have two 2nd Generation Body Composition Scales, setup as separate services.
![image](https://user-images.githubusercontent.com/89012202/215297265-dcceca5d-a763-420d-83bf-e5a0515b30b2.png)
Both scales are setup via Passive BLE monitor

For one of them, the entity values eventually change to an 'unknown' status until you activate/step on the scale. 
![image](https://user-images.githubusercontent.com/89012202/215296626-bd4cdde9-5dfe-440e-8eac-3c88c29f8056.png)

If you click on any of the entities, you can see a value in the history:
![image](https://user-images.githubusercontent.com/89012202/215296808-9a8f7c36-c8c7-4ca7-832b-f3692cece4c9.png)

The bodymiscale.person entity has a status of 'Problem' which coincides with these statuses, however i noticed that the Problem statuses align with when the other scale is used - Not able to replicate consistently.
I do not believe this is linked to any form of reboot of the rpi, as I noted in a few old issues, as the unknown status is retained after a reboot, and will change to unknown when no reboot occurs.
![image](https://user-images.githubusercontent.com/89012202/215297160-1b870a53-9d8d-43ed-81bd-10dcffbc1a74.png)

I can see the below error message, but unclear if related as it shows update when there are values.
```
Logger: frontend.js.latest.202301100
Source: components/system_log/__init__.py:256
First occurred: 1:34:12 PM (1 occurrences)
Last logged: 1:34:12 PM

http://<IP:PORT>/lovelace-body/thais-weight:0:0 Uncaught
```

**Comment by dckiller51** [comment]
Your scale should not be the weight sensor. You will need to create a template. 
Scale -> Sensor template -> Bodymiscale

**Comment by yeaaaaaahh** [comment]
@dckiller51, are you please able to provide an example of the sensor template?

If I understand this right, the Service Weight sensor should be the template sensor, and the template sensor should just be point at the BLE Monitor weight sensor?

**Comment by yeaaaaaahh** [comment]
I have created template sensors for both the scale weight, and scale impedance, but still seem to have the same problem.
I also noted I did not have the model: true set in the card.

```
template:
  - sensor:
    - name: "Shane weight template"
      unit_of_measurement: kg
      state: "{{ states('sensor.ble_weight_bedroom_scale') | round(2) }}"
  - sensor:
    - name: "Shane scale impedance template"
      unit_of_measurement: ohm
      state: "{{ states('sensor.ble_impedance_bedroom_scale') | round(2) }}"
  - sensor:
    - name: "Thais weight template"
      unit_of_measurement: kg
      state: "{{ states('sensor.ble_weight_bathroom_scale') | round(2) }}"
  - sensor:
    - name: "Thais scale impedance template"
      unit_of_measurement: ohm
      state: "{{ states('sensor.ble_impedance_bathroom_scale') | round(2) }}"
```

Reloading the integrations now fixes the one I reload, but breaks the other - So something not working quite correct between the two configurations.
