### ISSUE TITLE
ESP32 ble 

### ISSUE THREAD

**Issue by wifi75** [dckiller51/bodymiscale#21]
Hello I managed to integrate this component, it is not clear to me if I have to use this configuration in my esp32 module:
sensor:
```
  - platform: xiaomi_miscale2
    mac_address: '70:87:9E:2D:CD:52'
    weight:
      name: "Xiaomi Mi Scale 2 Peso"
      id: weight_miscale
      on_value:
        then:
          - lambda: |-
              if (id(weight_miscale).state >= 72 && id(weight_miscale).state <= 88.50) {
                return id(peso_tiziano).publish_state(x);}
              else if (id(weight_miscale).state >= 55.50 && id(weight_miscale).state <= 65) {
                return id(peso_alice).publish_state(x);}

    impedance:
      name: "Xiaomi Mi Scale Impedenza"
      id: impedance_xiaomi
      on_value:
        then:
          - lambda: |-
              if (id(weight_miscale).state >= 72 && id(weight_miscale).state <= 88.50) {
                return id(impedenza_tiziano).publish_state(x);}
              else if (id(weight_miscale).state >= 55.50 && id(weight_miscale).state <= 65) {
                return id(impedenza_alice).publish_state(x);}

  - platform: template
    name: Peso Tiziano
    id: peso_tiziano
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
  - platform: template
    name: Impedenza Tiziano
    id: impedenza_tiziano
    unit_of_measurement: 'ohm'
    icon: mdi:omega
    accuracy_decimals: 0
  - platform: template
    name: Peso Alice
    id: peso_alice
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
  - platform: template
    name: Impedenza Alice
    id: impedenza_alice
    unit_of_measurement: 'ohm'
    icon: mdi:omega
    accuracy_decimals: 0
```
