### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by fabir-git** [dckiller51/bodymiscale#22]
Since the Update to HomeAssistant core-2021.7.0 and core-2021.7.1 i get the following error with my sensors for the bodyscale:

```
Logger: homeassistant.helpers.event
Source: custom_components/bodymiscale/body_metrics.py:20
Integration: Bodymiscale (documentation)
First occurred: 16:00:38 (2 occurrences)
Last logged: 16:00:38
```

```
Error while processing state change for sensor.xiaomiscale1
Error while processing state change for sensor.xiaomiscale2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 272, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 432, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/bodymiscale/__init__.py", line 168, in _state_changed_event
    self.state_changed(event.data.get("entity_id"), event.data.get("new_state"))
  File "/config/custom_components/bodymiscale/__init__.py", line 191, in state_changed
    self._update_state()
  File "/config/custom_components/bodymiscale/__init__.py", line 218, in _update_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 455, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/bodymiscale/__init__.py", line 301, in state_attributes
    lib = body_metrics.bodyMetrics(weight, height, age, gender, impedance)
  File "/config/custom_components/bodymiscale/body_metrics.py", line 20, in __init__
    elif impedance > 3000:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by dckiller51** [comment]
No problem with me. Can you check your impedance sensor? it should not exceed 3000.

**Comment by fabir-git** [comment]
The impedance is in normal ranges (~800 and ~900).

**Comment by dckiller51** [comment]
I just tested on my test Hassio no problem. How did you implement or create your sensor impedance?

**Comment by fabir-git** [comment]
Config in HA (for XX the real height, birthday and gender is in the config):
```
bodymiscale:
    user1:
      sensors:
        weight: sensor.node_04_xiaomiscale_weight_user1
        impedance: sensor.node_04_xiaomiscale_impedance_user1
      height: XXX
      born: "XXXX-XX-XX"
      gender: "XXXXXXX"
      model_miscale: "181B"
     
    user2:
      sensors:
        weight: sensor.node_04_xiaomiscale_weight_user2
        impedance: sensor.node_04_xiaomiscale_impedance_user2
      height: XXX
      born: "XXX-XX-XX"
      gender: "XXXXXXX"
      model_miscale: "181B"
```

Config of my ESPHome Node (BLE), (for XX the real weight thresholds are in the config)
```
#XIAOMI SCALE
  - platform: xiaomi_miscale2
    mac_address: 'XX:XX:XX:XX:XX:XX'
    weight:
      name: "${devicename}_xiaomiscale_weight"
      id: weight_miscale
      on_value:
        then:
          - lambda: |-
              if (id(weight_miscale).state >= XX && id(weight_miscale).state <= XX) {
                return id(weight_user1).publish_state(x);}
              else if (id(weight_miscale).state >= XX && id(weight_miscale).state <= XX) {
                return id(weight_user2).publish_state(x);}
              else {
                return id(weight_none).publish_state(x);}
                
    impedance:
      name: "${devicename}_xiaomiscale_impedance"
      id: impedance_miscale
      on_value:
        then:
          - lambda: |-
              if (id(weight_miscale).state >= XX && id(weight_miscale).state <= XX) {
                return id(impedance_user1).publish_state(x);}
              else if (id(weight_miscale).state >= XX && id(weight_miscale).state <= XX) {
                return id(impedance_user2).publish_state(x);}
              else {
                return id(impedance_none).publish_state(x);}
```

**Comment by dckiller51** [comment]
Did you change the name of the sensor?

```
Error while processing state change for sensor.xiaomiscale1
Error while processing state change for sensor.xiaomiscale2
```
sensor.node_04_xiaomiscale_weight_user1
sensor.node_04_xiaomiscale_impedance_user1

**Comment by fabir-git** [comment]
Sadly that does not help:

`Error while processing state change for sensor.node_04_xiaomiscale_weight_user1
Error while processing state change for sensor.node_04_xiaomiscale_weight_user2`

**Comment by dckiller51** [comment]
What results do you have in the Home assistant sensors?

**Comment by fabir-git** [comment]
The results are completely normal:

494 Ohm
and
819 Ohm

**Comment by dckiller51** [comment]
Are your results good like this? I don't understand, I haven't changed anything. Did this work in your same setup before?

![Weight](https://user-images.githubusercontent.com/53062806/125168372-93c5cf80-e1a5-11eb-90f0-a83fde3cd859.png)
![impedance](https://user-images.githubusercontent.com/53062806/125168374-945e6600-e1a5-11eb-874d-31eaf486aa98.png)

**Comment by fabir-git** [comment]
![test](https://user-images.githubusercontent.com/62546027/125168809-89a4d080-e1a7-11eb-9373-aa1c3b8fc8d9.png)

**Comment by dckiller51** [comment]
Weight?

**Comment by fabir-git** [comment]
Sorry, there it is the same...
![Unbenannt](https://user-images.githubusercontent.com/62546027/125169243-90ccde00-e1a9-11eb-8b44-10236b67b743.png)
Everything worked for months with exact these settings...

**Comment by dckiller51** [comment]
Can you test yourself by deactivating other bodymiscal accounts

sensor:
```
- platform: template
  sensors:
    weight_test:
      friendly_name: "Test Weight"
      value_template: "76"
      unit_of_measurement: 'kg'
      icon_template: mdi:weight-kilogram
- platform: template
  sensors:
    impedance_test:
      friendly_name: "Test Impedance"
      value_template: "550"
      unit_of_measurement: 'ohm'
      icon_template: mdi:omega
```
bodymiscale:
```
test:
  sensors: 
    weight: sensor.weight_test
    impedance: sensor.impedance_test
  height: 166
  born: "2001-01-01"
  gender: "male"
  model_miscale: "181D"
```
