### ISSUE TITLE
2 User - User Entities have data but bodymiscale entitiy not 

### ISSUE THREAD

**Issue by evilmumi** [dckiller51/bodymiscale#235]
Hi, 
I have configured 2 User and they are getting data but only 1 have data in [bodymiscale] entitiy.
If a press reload than this user is active but only one at a time.
any ideas?
![image](https://github.com/dckiller51/bodymiscale/assets/23313699/7ccc40e9-0336-43e6-bd37-85854ad8395b)
![image](https://github.com/dckiller51/bodymiscale/assets/23313699/8687898b-859a-4c7b-b6c4-c110e781c509)
![image](https://github.com/dckiller51/bodymiscale/assets/23313699/c218df79-4996-43b8-8e0a-217b0dc5d634)

**Comment by evilmumi** [comment]
any ideas / news on that?

**Comment by lifeexplore** [comment]
some with me. only one person bodymiscale entity could be active.

**Comment by lifeexplore** [comment]
It's worked! Everything is ok. Tks!

**Comment by evilmumi** [comment]
> It's worked! Everything is ok. Tks!

what did you to fix it?
can you please share code

**Comment by phil-schneider** [comment]
@lifeexplore what did you Do?

**Comment by cranky-coder** [comment]
So someone figured it out and didn't share or close out the issue?  Im having same issue to and it's quite weird.

**Comment by dckiller51** [comment]
@cranky-coder 

I've been looking for a solution to this problem for a few days. For me, it's due to a bad configuration. Look at my reworked readme. You should have a dedicated sensor for each user. I managed to solve the problem by adding a json that stores the last weight received for each user, but I find it too cumbersome in the management of the component. I have another idea, but for now I haven't managed to implement it.

I would like your detailed configuration to reproduce the problem at home. Since I have 5 users, no problem at home. Then I chose a very different approach. I weigh myself and then I receive an HA notification to choose who has just weighed themselves. I use Node Red for the implementation.

https://github.com/dckiller51/bodymiscale/blob/beta/README.md

**Comment by cranky-coder** [comment]
Here is what I have.  

I have my esphome configured like so.

`- platform: xiaomi_miscale
    mac_address: 'D0:3E:7D:0E:DF:45'
    weight:
      name: "Xiaomi Mi Scale Weight"
      id: weight_miscale
      on_value:
        then:
          - lambda: |-
              if (id(weight_miscale).state < 90) {
                return id(weight_user2).publish_state(x);}
              else if (id(weight_miscale).state >= 90) {
                return id(weight_user1).publish_state(x);}
    
   
    impedance:
      name: "Xiaomi Mi Scale Impedance"
      id: impedance_miscale
      on_value:
        then:
          - lambda: |-
              if (id(weight_miscale).state < 90) {
                return id(impedance_user2).publish_state(x) ;}
              else if (id(weight_miscale).state >= 90) {
                return id(impedance_user1).publish_state(x) ;}
                
  - platform: template
    name: Weight User1 (kg)
    id: weight_user1
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
  - platform: template
    name: Impedance User1
    id: impedance_user1
    unit_of_measurement: 'ohm'
    icon: mdi:omega
    accuracy_decimals: 0
  - platform: template
    name: Weight User2 (kg))
    id: weight_user2
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
  - platform: template
    name: Impedance User2
    id: impedance_user2
    unit_of_measurement: 'ohm'
    icon: mdi:omega
    accuracy_decimals: 0`

Then in home assistant I have created 4 helpers (2 users x 2 sensors weight/impedance) those are just template helpers that mimic the real sensors but survive through reboots ect.

Then I configure the bodymiscale integration for the 2 users using their dedicated helper sensors.

I have 2 cards on a page showing the 2 users.  

![Image](https://github.com/user-attachments/assets/1e6791c4-935e-4db3-8955-942f3e227e9a)

Which ever one had the integration loaded last actually loads.  The other one shows unavailable.

**Comment by dckiller51** [comment]
@cranky-coder 
I have to go to work, but here's a first example. You actually use the first example when adding the scale to ESPHOME. I did this at the very beginning, but this model actually resets the other user's weight and vice versa.

I'll add some variables to simplify the configuration. This version will allow everything to be managed via esphome without losing data in case of HA or even ESPHOME reboot.

Then I will update the readme to help everyone.

```
number:
  - platform: template
    name: "Weight User 1"
    id: weight_user1
    restore_value: true
    optimistic: true
    min_value: 0
    max_value: 200
    step: 0.1
    unit_of_measurement: 'kg'

  - platform: template
    name: "Impedance User 1"
    id: impedance_user1
    restore_value: true
    optimistic: true
    min_value: 0
    max_value: 1000
    step: 0.1
    unit_of_measurement: 'ohm'

  - platform: template
    name: "Weight User 2"
    id: weight_user2
    restore_value: true
    optimistic: true
    min_value: 0
    max_value: 200
    step: 0.1
    unit_of_measurement: 'kg'

  - platform: template
    name: "Impedance User 2"
    id: impedance_user2
    restore_value: true
    optimistic: true
    min_value: 0
    max_value: 1000
    step: 0.1
    unit_of_measurement: 'ohm'

sensor:
  # Capteur de poids User 1
  - platform: template
    name: "Weight Sensor User 1"
    id: weight_sensor_user1
    unit_of_measurement: 'kg'
    lambda: 'return id(weight_user1).state;'

  # Capteur d'impédance User 1
  - platform: template
    name: "Impedance Sensor User 1"
    id: impedance_sensor_user1
    unit_of_measurement: 'ohm'
    lambda: 'return id(impedance_user1).state;'

  # Capteur de poids User 2
  - platform: template
    name: "Weight Sensor User 2"
    id: weight_sensor_user2
    unit_of_measurement: 'kg'
    lambda: 'return id(weight_user2).state;'

  # Capteur d'impédance User 2
  - platform: template
    name: "Impedance Sensor User 2"
    id: impedance_sensor_user2
    unit_of_measurement: 'ohm'
    lambda: 'return id(impedance_user2).state;'

  # Capteur Xiaomi Mi Scale (Poids)
  - platform: xiaomi_miscale
    mac_address: '5C:CA:D3:70:D4:A2'
    weight:
      name: "Xiaomi Mi Scale Weight"
      id: xiaomi_weight
      on_value:
        then:
          - if:
              condition:
                lambda: 'return (id(xiaomi_weight).state >= 50) && (id(xiaomi_weight).state <= 72.99);'
              then:
                - number.set:
                    id: weight_user1
                    value: !lambda 'return id(xiaomi_weight).state;'
                - number.set:
                    id: impedance_user1
                    value: !lambda 'return id(xiaomi_impedance).state;'
          - if:
              condition:
                lambda: 'return (id(xiaomi_weight).state >= 73) && (id(xiaomi_weight).state <= 100);'
              then:
                - number.set:
                    id: weight_user2
                    value: !lambda 'return id(xiaomi_weight).state;'
                - number.set:
                    id: impedance_user2
                    value: !lambda 'return id(xiaomi_impedance).state;'

  # Capteur d'impédance Xiaomi Mi Scale
  - platform: xiaomi_miscale
    mac_address: '5C:CA:D3:70:D4:A2'
    impedance:
      name: "Xiaomi Mi Scale Impedance"
      id: xiaomi_impedance
```

**Comment by cranky-coder** [comment]
I have updated my esphome config.  I have updated my configs for the integration to point to the dedicated sensors.  What version of the integration should i use?  hacs still shows the "standard" release is 2024.6 but i see the beta's out there.

**Comment by cranky-coder** [comment]
I tried adding beta, and even with the updates the esphome and using the dedicated sensors, the cards will only show 1 active integration, the other one goes unavailable.  

![Image](https://github.com/user-attachments/assets/de969e90-d3a7-4ef5-aa3f-d94e64da2e65)

![Image](https://github.com/user-attachments/assets/a6528d5c-c8da-4d69-9c2c-3e84d7be39e8)

Just switches back and forth depending on which one was reloaded last.

**Comment by dckiller51** [comment]
You can use the latest versions no worries.

you only change the numbers between 50 - 72.99 and 73 - 100. as well as your mac address?

**Comment by cranky-coder** [comment]
that is correct, and the bodymiscale integration still only loads 1 at a time.  if i do "reload" on User 1, then User 2 goes unavailable and vice versa.

**Comment by dckiller51** [comment]
I just tested and improved this version. Change only the part in substitutions: . In bodymiscale you must update sensors with sensor.xiaomi_miscale_weight_xxx ... Restart home assistant. Normally if you weigh yourself it should work. I restarted HA, restarted eshome the data remains present.

```
esphome:
  name: xiaomi_miscale
  friendly_name: xiaomi_miscale 

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret ssid
  password: !secret wpa2
  fast_connect: true

captive_portal:  

logger:

api:

ota:
  - platform: esphome
    password: !secret ota_password

esp32_ble_tracker:

time:
  - platform: homeassistant
    id: esptime

# Configuration
substitutions:
  mac_address: "5C:CA:D3:70:D4:A2"
  user1_name: "Aurelien"
  weight_user1_min: "50"
  weight_user1_max: "72.99"
  user2_name: "Noham"
  weight_user2_min: "73"
  weight_user2_max: "100"

text:
  - platform: template
    name: "Last Time Measurement TXT ${user1_name}"
    id: last_time_measurement_txt_user1
    optimistic: true
    restore_value: true
    max_length: 20
    mode: text

  - platform: template
    name: "Last Time Measurement TXT ${user2_name}"
    id: last_time_measurement_txt_user2
    optimistic: true
    restore_value: true
    max_length: 20
    mode: text

number:
  - platform: template
    name: "Weight Num ${user1_name}"
    id: weight_num_user1
    restore_value: true
    optimistic: true
    min_value: 0
    max_value: 200
    step: 0.1
    unit_of_measurement: 'kg'
    internal: true

  - platform: template
    name: "Impedance Num ${user1_name}"
    id: impedance_num_user1
    restore_value: true
    optimistic: true
    min_value: 0
    max_value: 1000
    step: 0.1
    unit_of_measurement: 'ohm'
    internal: true

  - platform: template
    name: "Weight Num ${user2_name}"
    id: weight_num_user2
    restore_value: true
    optimistic: true
    min_value: 0
    max_value: 200
    step: 0.1
    unit_of_measurement: 'kg'
    internal: true

  - platform: template
    name: "Impedance Num ${user2_name}"
    id: impedance_num_user2
    restore_value: true
    optimistic: true
    min_value: 0
    max_value: 1000
    step: 0.1
    unit_of_measurement: 'ohm'
    internal: true

sensor:
  # Weight sensor User 1
  - platform: template
    name: "Weight ${user1_name}"
    id: weight_user1
    unit_of_measurement: 'kg'
    lambda: 'return id(weight_num_user1).state;'

  # Impedance sensor User 1
  - platform: template
    name: "Impedance ${user1_name}"
    id: impedance_user1
    unit_of_measurement: 'ohm'
    lambda: 'return id(impedance_num_user1).state;'

  # Weight sensor User 2
  - platform: template
    name: "Weight ${user2_name}"
    id: weight_user2
    unit_of_measurement: 'kg'
    lambda: 'return id(weight_num_user2).state;'

  # Impedance sensor User 2
  - platform: template
    name: "Impedance ${user2_name}"
    id: impedance_user2
    unit_of_measurement: 'ohm'
    lambda: 'return id(impedance_num_user2).state;'

  # Weight sensor Xiaomi Mi Scale
  - platform: xiaomi_miscale
    mac_address: ${mac_address}
    weight:
      name: "Xiaomi Mi Scale Weight"
      id: xiaomi_weight
      on_value:
        then:
          - if:
              condition:
                lambda: 'return (id(xiaomi_weight).state >= atof("${weight_user1_min}")) && (id(xiaomi_weight).state <= atof("${weight_user1_max}"));'
              then:
                - number.set:
                    id: weight_num_user1
                    value: !lambda 'return id(xiaomi_weight).state;'
                - number.set:
                    id: impedance_num_user1
                    value: !lambda 'return id(xiaomi_impedance).state;'
                - text.set:
                    id: last_time_measurement_txt_user1
                    value: !lambda 'return id(esptime).now().strftime("%Y-%m-%d %H:%M");'
          - if:
              condition:
                lambda: 'return (id(xiaomi_weight).state >= atof("${weight_user2_min}")) && (id(xiaomi_weight).state <= atof("${weight_user2_max}"));'
              then:
                - number.set:
                    id: weight_num_user2
                    value: !lambda 'return id(xiaomi_weight).state;'
                - number.set:
                    id: impedance_num_user2
                    value: !lambda 'return id(xiaomi_impedance).state;'
                - text.set:
                    id: last_time_measurement_txt_user2
                    value: !lambda 'return id(esptime).now().strftime("%Y-%m-%d %H:%M");'

  # Impedance sensor Xiaomi Mi Scale
  - platform: xiaomi_miscale
    mac_address: ${mac_address}
    impedance:
      name: "Xiaomi Mi Scale Impedance"
      id: xiaomi_impedance
```

**Comment by dckiller51** [comment]
Here's my final suggestion for users who want to integrate sensors into Esphome. I've tested it thoroughly, and the data is still there. By default, you have two users, but I've added the ability to add up to five users; for this, you'll need to uncomment (#) accordingly.

```
esphome:
  name: xiaomi_miscale
  friendly_name: xiaomi_miscale 

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret ssid
  password: !secret wpa2
  fast_connect: true

captive_portal:  

logger:

api:

ota:
  - platform: esphome
    password: !secret ota_password

esp32_ble_tracker:

time:
  - platform: homeassistant
    id: esptime

# Configuration
substitutions:
  mac_address: "5C:CA:D3:70:D4:A2"
  user1_name: "Aurelien"
  weight_user1_min: "70"
  weight_user1_max: "74.99"
  user2_name: "Noham"
  weight_user2_min: "20"
  weight_user2_max: "30"
  #user3_name: "Name3"
  #weight_user3_min: "60"
  #weight_user3_max: "69.99"
  #user4_name: "Name4"
  #weight_user4_min: "75"
  #weight_user4_max: "79.99"
  #user5_name: "Name5"
  #weight_user5_min: "50"
  #weight_user5_max: "59.99"

number:
  #User1
  - platform: template
    name: "Weight Num ${user1_name}"
    id: weight_num_user1
    restore_value: true
    optimistic: true
    min_value: 0
    max_value: 200
    step: 0.1
    unit_of_measurement: 'kg'
    internal: true

  - platform: template
    name: "Impedance Num ${user1_name}"
    id: impedance_num_user1
    restore_value: true
    optimistic: true
    min_value: 0
    max_value: 1000
    step: 0.1
    unit_of_measurement: 'ohm'
    internal: true
  
  - platform: template
    name: "Last Time Measurement Num ${user1_name}"
    id: last_time_measurement_num_user1
    min_value: 0
    max_value: 4294967295
    step: 0.1
    optimistic: true
    restore_value: true
    internal: true

  #User2
  - platform: template
    name: "Weight Num ${user2_name}"
    id: weight_num_user2
    restore_value: true
    optimistic: true
    min_value: 0
    max_value: 200
    step: 0.1
    unit_of_measurement: 'kg'
    internal: true

  - platform: template
    name: "Impedance Num ${user2_name}"
    id: impedance_num_user2
    restore_value: true
    optimistic: true
    min_value: 0
    max_value: 1000
    step: 0.1
    unit_of_measurement: 'ohm'
    internal: true

  - platform: template
    name: "Last Time Measurement Num ${user2_name}"
    id: last_time_measurement_num_user2
    min_value: 0
    max_value: 4294967295
    step: 0.1
    optimistic: true
    restore_value: true
    internal: true

  #User3
  #- platform: template
  #  name: "Weight Num ${user3_name}"
  #  id: weight_num_user3
  #  restore_value: true
  #  optimistic: true
  #  min_value: 0
  #  max_value: 200
  #  step: 0.1
  #  unit_of_measurement: 'kg'
  #  internal: true

  #- platform: template
  #  name: "Impedance Num ${user3_name}"
  #  id: impedance_num_user3
  #  restore_value: true
  #  optimistic: true
  #  min_value: 0
  #  max_value: 1000
  #  step: 0.1
  #  unit_of_measurement: 'ohm'
  #  internal: true
  
  #- platform: template
  #  name: "Last Time Measurement Num ${user3_name}"
  #  id: last_time_measurement_num_user3
  #  min_value: 0
  #  max_value: 4294967295
  #  step: 0.1
  #  optimistic: true
  #  restore_value: true
  #  internal: true

  #User4
  #- platform: template
  #  name: "Weight Num ${user4_name}"
  #  id: weight_num_user4
  #  restore_value: true
  #  optimistic: true
  #  min_value: 0
  #  max_value: 200
  #  step: 0.1
  #  unit_of_measurement: 'kg'
  #  internal: true

  #- platform: template
  #  name: "Impedance Num ${user4_name}"
  #  id: impedance_num_user4
  #  restore_value: true
  #  optimistic: true
  #  min_value: 0
  #  max_value: 1000
  #  step: 0.1
  #  unit_of_measurement: 'ohm'
  #  internal: true
  
  #- platform: template
  #  name: "Last Time Measurement Num ${user4_name}"
  #  id: last_time_measurement_num_user4
  #  min_value: 0
  #  max_value: 4294967295
  #  step: 0.1
  #  optimistic: true
  #  restore_value: true
  #  internal: true

  #User5
  #- platform: template
  #  name: "Weight Num ${user5_name}"
  #  id: weight_num_user5
  #  restore_value: true
  #  optimistic: true
  #  min_value: 0
  #  max_value: 200
  #  step: 0.1
  #  unit_of_measurement: 'kg'
  #  internal: true

  #- platform: template
  #  name: "Impedance Num ${user5_name}"
  #  id: impedance_num_user5
  #  restore_value: true
  #  optimistic: true
  #  min_value: 0
  #  max_value: 1000
  #  step: 0.1
  #  unit_of_measurement: 'ohm'
  #  internal: true
  
  #- platform: template
  #  name: "Last Time Measurement Num ${user5_name}"
  #  id: last_time_measurement_num_user5
  #  min_value: 0
  #  max_value: 4294967295
  #  step: 0.1
  #  optimistic: true
  #  restore_value: true
  #  internal: true

sensor:
  # Weight sensor User 1
  - platform: template
    name: "Weight ${user1_name}"
    id: weight_user1
    unit_of_measurement: 'kg'
    icon: mdi:scale-bathroom
    accuracy_decimals: 2
    state_class: measurement
    lambda: 'return id(weight_num_user1).state;'

  # Impedance sensor User 1
  - platform: template
    name: "Impedance ${user1_name}"
    id: impedance_user1
    unit_of_measurement: 'ohm'
    icon: mdi:omega
    state_class: measurement
    accuracy_decimals: 0
    lambda: 'return id(impedance_num_user1).state;'

  # Last Measurement Time sensor User 1
  - platform: template
    name: "Last Time Measurement ${user1_name}"
    id: last_time_measurement_user1
    lambda: 'return id(last_time_measurement_num_user1).state;'
    device_class: timestamp

  # Weight sensor User 2
  - platform: template
    name: "Weight ${user2_name}"
    id: weight_user2
    unit_of_measurement: 'kg'
    icon: mdi:scale-bathroom
    state_class: measurement
    accuracy_decimals: 2
    lambda: 'return id(weight_num_user2).state;'

  # Impedance sensor User 2
  - platform: template
    name: "Impedance ${user2_name}"
    id: impedance_user2
    unit_of_measurement: 'ohm'
    icon: mdi:omega
    state_class: measurement
    accuracy_decimals: 0
    lambda: 'return id(impedance_num_user2).state;'

  # Last Measurement Time sensor User 2 
  - platform: template
    name: "Last Time Measurement ${user2_name}"
    id: last_time_measurement_user2
    lambda: 'return id(last_time_measurement_num_user2).state;'
    device_class: timestamp

  # Weight sensor User 3
  #- platform: template
  #  name: "Weight ${user3_name}"
  #  id: weight_user3
  #  unit_of_measurement: 'kg'
  #  icon: mdi:scale-bathroom
  #  state_class: measurement
  #  accuracy_decimals: 2
  #  lambda: 'return id(weight_num_user3).state;'

  # Impedance sensor User 3
  #- platform: template
  #  name: "Impedance ${user3_name}"
  #  id: impedance_user3
  #  unit_of_measurement: 'ohm'
  #  icon: mdi:omega
  #  state_class: measurement
  #  accuracy_decimals: 0
  #  lambda: 'return id(impedance_num_user3).state;'

  # Last Measurement Time sensor User 3
  #- platform: template
  #  name: "Last Time Measurement ${user3_name}"
  #  id: last_time_measurement_user3
  #  lambda: 'return id(last_time_measurement_num_user3).state;'
  #  device_class: timestamp

  # Weight sensor user 4
  #- platform: template
  #  name: "Weight ${user4_name}"
  #  id: weight_user4
  #  unit_of_measurement: 'kg'
  #  icon: mdi:scale-bathroom
  #  state_class: measurement
  #  accuracy_decimals: 2
  #  lambda: 'return id(weight_num_user4).state;'

  # Impedance sensor user 4
  #- platform: template
  #  name: "Impedance ${user4_name}"
  #  id: impedance_user4
  #  unit_of_measurement: 'ohm'
  #  icon: mdi:omega
  #  state_class: measurement
  #  accuracy_decimals: 0
  #  lambda: 'return id(impedance_num_user4).state;'

  # Last Measurement Time sensor user 4 
  #- platform: template
  #  name: "Last Time Measurement ${user4_name}"
  #  id: last_time_measurement_user4
  #  lambda: 'return id(last_time_measurement_num_user4).state;'
  #  device_class: timestamp

  # Weight sensor user 5
  #- platform: template
  #  name: "Weight ${user5_name}"
  #  id: weight_user5
  #  unit_of_measurement: 'kg'
  #  icon: mdi:scale-bathroom
  #  state_class: measurement
  #  accuracy_decimals: 2
  #  lambda: 'return id(weight_num_user5).state;'

  # Impedance sensor user 5
  #- platform: template
  #  name: "Impedance ${user5_name}"
  #  id: impedance_user5
  #  unit_of_measurement: 'ohm'
  #  icon: mdi:omega
  #  state_class: measurement
  #  accuracy_decimals: 0
  #  lambda: 'return id(impedance_num_user5).state;'

  # Last Measurement Time sensor user 5 
  #- platform: template
  #  name: "Last Time Measurement ${user5_name}"
  #  id: last_time_measurement_user5
  #  lambda: 'return id(last_time_measurement_num_user5).state;'
  #  device_class: timestamp

  # Weight sensor Xiaomi Mi Scale
  - platform: xiaomi_miscale
    mac_address: ${mac_address}
    weight:
      name: "Xiaomi Mi Scale Weight"
      id: xiaomi_weight
      on_value:
        then:
          - if:
              condition:
                lambda: 'return (id(xiaomi_weight).state >= atof("${weight_user1_min}")) && (id(xiaomi_weight).state <= atof("${weight_user1_max}"));'
              then:
                - number.set:
                    id: weight_num_user1
                    value: !lambda 'return id(xiaomi_weight).state;'
                - number.set:
                    id: last_time_measurement_num_user1
                    value: !lambda 'return id(esptime).now().timestamp;'
          - if:
              condition:
                lambda: 'return (id(xiaomi_weight).state >= atof("${weight_user2_min}")) && (id(xiaomi_weight).state <= atof("${weight_user2_max}"));'
              then:
                - number.set:
                    id: weight_num_user2
                    value: !lambda 'return id(xiaomi_weight).state;'
                - number.set:
                    id: last_time_measurement_num_user2
                    value: !lambda 'return id(esptime).now().timestamp;'
          #- if:
          #    condition:
          #      lambda: 'return (id(xiaomi_weight).state >= atof("${weight_user3_min}")) && (id(xiaomi_weight).state <= atof("${weight_user3_max}"));'
          #    then:
          #      - number.set:
          #          id: weight_num_user3
          #          value: !lambda 'return id(xiaomi_weight).state;'
          #      - number.set:
          #          id: last_time_measurement_num_user3
          #          value: !lambda 'return id(esptime).now().timestamp;'
          #- if:
          #    condition:
          #      lambda: 'return (id(xiaomi_weight).state >= atof("${weight_user4_min}")) && (id(xiaomi_weight).state <= atof("${weight_user4_max}"));'
          #    then:
          #      - number.set:
          #          id: weight_num_user4
          #          value: !lambda 'return id(xiaomi_weight).state;'
          #      - number.set:
          #          id: last_time_measurement_num_user4
          #          value: !lambda 'return id(esptime).now().timestamp;'
          #- if:
          #    condition:
          #      lambda: 'return (id(xiaomi_weight).state >= atof("${weight_user5_min}")) && (id(xiaomi_weight).state <= atof("${weight_user5_max}"));'
          #    then:
          #      - number.set:
          #          id: weight_num_user5
          #          value: !lambda 'return id(xiaomi_weight).state;'
          #      - number.set:
          #          id: last_time_measurement_num_user5
          #          value: !lambda 'return id(esptime).now().timestamp;'
    # Impedance sensor Xiaomi Mi Scale
    impedance:
      name: "Xiaomi Mi Scale Impedance"
      id: xiaomi_impedance
      on_value:
        then:
          - if:
              condition:
                lambda: 'return (id(xiaomi_weight).state >= atof("${weight_user1_min}")) && (id(xiaomi_weight).state <= atof("${weight_user1_max}"));'
              then:
                - number.set:
                    id: impedance_num_user1
                    value: !lambda 'return id(xiaomi_impedance).state;'
          - if:
              condition:
                lambda: 'return (id(xiaomi_weight).state >= atof("${weight_user2_min}")) && (id(xiaomi_weight).state <= atof("${weight_user2_max}"));'
              then:
                - number.set:
                    id: impedance_num_user2
                    value: !lambda 'return id(xiaomi_impedance).state;'
          #- if:
          #    condition:
          #      lambda: 'return (id(xiaomi_weight).state >= atof("${weight_user3_min}")) && (id(xiaomi_weight).state <= atof("${weight_user3_max}"));'
          #    then:
          #      - number.set:
          #          id: impedance_num_user3
          #          value: !lambda 'return id(xiaomi_impedance).state;'
          #- if:
          #    condition:
          #      lambda: 'return (id(xiaomi_weight).state >= atof("${weight_user4_min}")) && (id(xiaomi_weight).state <= atof("${weight_user4_max}"));'
          #    then:
          #      - number.set:
          #          id: impedance_num_user4
          #          value: !lambda 'return id(xiaomi_impedance).state;'
          #- if:
          #    condition:
          #      lambda: 'return (id(xiaomi_weight).state >= atof("${weight_user5_min}")) && (id(xiaomi_weight).state <= atof("${weight_user5_max}"));'
          #    then:
          #      - number.set:
          #          id: impedance_num_user5
          #          value: !lambda 'return id(xiaomi_impedance).state;'
```
