### ISSUE TITLE
Is there a min weight limit?

### ISSUE THREAD

**Issue by Phoenix-DH** [dckiller51/bodymiscale#271]
Hey @dckiller51,

I was just not checking the blueprint you provided. For me and my wife all is ok. Now we tried out 1 year old daughter wirh 8.15kg.

I think everything is correct configured:
Blueprint - Automation:
![Image](https://github.com/user-attachments/assets/84a9fb65-3b2e-4e6e-a23b-97740fc72b39)

The created helpers have also the values:
![Image](https://github.com/user-attachments/assets/d04595fd-c344-4bab-9c13-2badd0a774c5)
![Image](https://github.com/user-attachments/assets/7b2eed54-9ae7-4550-adbf-37abc4378528)

And the configuration in bodymiscale:
![Image](https://github.com/user-attachments/assets/458219e0-4314-47ee-a76b-dba256fefe5c)

But the result is only that:
![Image](https://github.com/user-attachments/assets/6fd5d378-b71a-450a-af92-6aeb9a384aac)

Currently I think the config is fine, have it for 3 others too. Only this one is not working.

Thanks.

**Comment by dckiller51** [comment]
Hello, I didn't set a weight limit. However, you have to make sure you set the correct number of users. Then there's a 15-second wait to ensure the impedance is captured. Since these are young children, the scale may have more difficulty stabilizing (this is a guess). You can manually add the weight for your child's sensor to ensure the bodymiscale component is working properly. I'm no expert, but I don't think the impedance is useful for a child; I think it's valid from a certain age.

**Comment by dckiller51** [comment]
Check that you have not set a minimum value to the input_number.

![Image](https://github.com/user-attachments/assets/08e6326f-ba8e-41bb-befe-fc54788ced66)

**Comment by dckiller51** [comment]
Hello, I just tested the blueprint. No problem regaining the weight, but there is indeed a minimum limit in Bodymiscale of 10 kg. It should still accept it with a low weight problem message.


Below is an excerpt from the blueprint execution history. You can see this in automation "trace"

```
Executed: April 9, 2025 at 8:45:16 AM
Result:
params:
  domain: input_number
  service: set_value
  service_data:
    value: 8.15
    entity_id:
      - input_number.weight_aurelien
  target:
    entity_id:
      - input_number.weight_aurelien
running_script: false
```
