### ISSUE TITLE
Error on boot

### ISSUE THREAD

**Issue by benquan** [dckiller51/bodymiscale#30]
I am always getting this error on boot. But the integration works fine after that.

    Logger: homeassistant.helpers.event
    Source: custom_components/bodymiscale/body_metrics.py:20
    Integration: Bodymiscale (documentation)
    First occurred: 9:33:01 AM (1 occurrences)
    Last logged: 9:33:01 AM
    
    Error while processing state change for sensor.ben_weight_kg
    Traceback (most recent call last):
      File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 272, in _async_state_change_dispatcher
        hass.async_run_hass_job(job, event)
      File "/usr/src/homeassistant/homeassistant/core.py", line 433, in async_run_hass_job
        hassjob.target(*args)
      File "/config/custom_components/bodymiscale/__init__.py", line 169, in _state_changed_event
        self.state_changed(event.data.get("entity_id"), event.data.get("new_state"))
      File "/config/custom_components/bodymiscale/__init__.py", line 192, in state_changed
        self._update_state()
      File "/config/custom_components/bodymiscale/__init__.py", line 219, in _update_state
        self.async_write_ha_state()
      File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
        self._async_write_ha_state()
      File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 500, in _async_write_ha_state
        attr.update(self.state_attributes or {})
      File "/config/custom_components/bodymiscale/__init__.py", line 305, in state_attributes
        lib = body_metrics.bodyMetrics(weight, height, age, gender, impedance)
      File "/config/custom_components/bodymiscale/body_metrics.py", line 20, in __init__
        elif impedance > 3000:
    TypeError: '>' not supported between instances of 'NoneType' and 'int'

this is my config:

    bodymiscale:
      ben:
        sensors:
          weight: sensor.ben_weight_kg
          impedance: sensor.ben_impedance
        height: 165
        born: "1975-02-05"
        gender: "male"
        model_miscale: "181B"

and my scale reports me in Lbs so I have to convert it to kg before using bodymisle using the following:  ben_weight_kg is defined as a **template**:

    sensor:
      - name: ben_weight_kg
        unique_id: ben_weight_kg
        unit_of_measurement: "kg"
        icon: mdi:weight-kilogram
        state_class: measurement
        state: >
          {% set weight = states('sensor.ble_weight') | float %}
          {% if 135 <= weight <= 150 %}
            {{ (states('sensor.ble_weight') | float / 2.20462) | round(1)}}
          {% else %}
            {{ states("sensor.ben_weight_kg") }}
          {% endif %}

finally the sensor.ble_weight is comming from **Passive BLE monitor integration**

<img width="407" alt="Screen Shot 2021-09-08 at 12 31 32 PM" src="https://user-images.githubusercontent.com/3030645/132565391-41309ca8-a387-4e36-a5ff-4d402252660a.png">

Also whenever I do not record a weight for more that 24hrs and I do a system reboot, all values go to 0. If I have measuered within 24hrs then all is fine.

Thanks

Ben

**Comment by dckiller51** [comment]
@benquan This is because the sensor does not keep the value in memory after the reboot. My advice is to switch to a sensor per node red. Install the companion https://github.com/zachowj/hass-node-red. 
Watch my node for inspiration.
https://community.home-assistant.io/t/exemple-xiaomi-miscale-select-the-person-who-weighs-himself-notif-action/299321
Since then I have no more problems

**Comment by xbmcnut** [comment]
This was my solution https://github.com/dckiller51/bodymiscale/issues/31#issuecomment-917733640

**Comment by benquan** [comment]
I did something similar to solve the "resetting value" but instead of MQTT, I used helpers (input_number).

```
bodymiscale:
  ben:
    sensors:
      weight: input_number.ben_weight_kg
      impedance: input_number.ben_impedance
    height: 165
    born: "1975-02-05"
    gender: "male"
    model_miscale: "181B"
```

and then an automation:

```
alias: Ben Weight
description: ''
trigger:
  - platform: state
    entity_id: sensor.ble_weight, sensor.ble_impedance
condition:
  - condition: template
    value_template: >-
      {{ trigger.to_state and trigger.from_state and trigger.to_state.state !=
      trigger.from_state.state }}
  - condition: numeric_state
    entity_id: sensor.ble_weight
    above: '135'
    below: '145'
action:
  - service: input_number.set_value
    target:
      entity_id: input_number.ben_weight_kg
    data:
      value: '{{ states(''sensor.ble_weight'')|float  / 2.20462 }}'
  - service: input_number.set_value
    target:
      entity_id: input_number.ben_impedance
    data:
      value: '{{ states(''sensor.ble_impedance'')|int }}'
```

It all works as expected, but I am still getting the error nagging error boot:
```
Logger: homeassistant.helpers.event
Source: custom_components/bodymiscale/body_metrics.py:20
Integration: Bodymiscale (documentation)
First occurred: 12:45:09 AM (1 occurrences)
Last logged: 12:45:09 AM

Error while processing state change for input_number.ben_weight_kg
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 272, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 433, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/bodymiscale/__init__.py", line 169, in _state_changed_event
    self.state_changed(event.data.get("entity_id"), event.data.get("new_state"))
  File "/config/custom_components/bodymiscale/__init__.py", line 192, in state_changed
    self._update_state()
  File "/config/custom_components/bodymiscale/__init__.py", line 219, in _update_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 500, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/bodymiscale/__init__.py", line 305, in state_attributes
    lib = body_metrics.bodyMetrics(weight, height, age, gender, impedance)
  File "/config/custom_components/bodymiscale/body_metrics.py", line 20, in __init__
    elif impedance > 3000:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

Values after boot are fine, but I always get the message in the log

The error seems to point towards the impedance being type 'NoneType'? Is it that bodymiscale is running before the input_number gets restored?

**Comment by dckiller51** [comment]
> I did something similar to solve the "resetting value" but instead of MQTT, I used helpers (input_number).
> 
> ```
> bodymiscale:
>   ben:
>     sensors:
>       weight: input_number.ben_weight_kg
>       impedance: input_number.ben_impedance
>     height: 165
>     born: "1975-02-05"
>     gender: "male"
>     model_miscale: "181B"
> ```
> 
> and then an automation:
> 
> ```
> alias: Ben Weight
> description: ''
> trigger:
>   - platform: state
>     entity_id: sensor.ble_weight, sensor.ble_impedance
> condition:
>   - condition: template
>     value_template: >-
>       {{ trigger.to_state and trigger.from_state and trigger.to_state.state !=
>       trigger.from_state.state }}
>   - condition: numeric_state
>     entity_id: sensor.ble_weight
>     above: '135'
>     below: '145'
> action:
>   - service: input_number.set_value
>     target:
>       entity_id: input_number.ben_weight_kg
>     data:
>       value: '{{ states(''sensor.ble_weight'')|float  / 2.20462 }}'
>   - service: input_number.set_value
>     target:
>       entity_id: input_number.ben_impedance
>     data:
>       value: '{{ states(''sensor.ble_impedance'')|int }}'
> ```
> 
> It all works as expected, but I am still getting the error nagging error boot:
> 
> ```
> Logger: homeassistant.helpers.event
> Source: custom_components/bodymiscale/body_metrics.py:20
> Integration: Bodymiscale (documentation)
> First occurred: 12:45:09 AM (1 occurrences)
> Last logged: 12:45:09 AM
> 
> Error while processing state change for input_number.ben_weight_kg
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 272, in _async_state_change_dispatcher
>     hass.async_run_hass_job(job, event)
>   File "/usr/src/homeassistant/homeassistant/core.py", line 433, in async_run_hass_job
>     hassjob.target(*args)
>   File "/config/custom_components/bodymiscale/__init__.py", line 169, in _state_changed_event
>     self.state_changed(event.data.get("entity_id"), event.data.get("new_state"))
>   File "/config/custom_components/bodymiscale/__init__.py", line 192, in state_changed
>     self._update_state()
>   File "/config/custom_components/bodymiscale/__init__.py", line 219, in _update_state
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 500, in _async_write_ha_state
>     attr.update(self.state_attributes or {})
>   File "/config/custom_components/bodymiscale/__init__.py", line 305, in state_attributes
>     lib = body_metrics.bodyMetrics(weight, height, age, gender, impedance)
>   File "/config/custom_components/bodymiscale/body_metrics.py", line 20, in __init__
>     elif impedance > 3000:
> TypeError: '>' not supported between instances of 'NoneType' and 'int'
> ```
> 
> Values after boot are fine, but I always get the message in the log
> 
> The error seems to point towards the impedance being type 'NoneType'? Is it that bodymiscale is running before the input_number gets restored?

I think your problem is that your input_numbre must be acceptable after the custom_components.
Can you give it a try with a sensor template.

```
- platform: template
  sensors:
    ben_weight_kg:
      friendly_name: "BEN WEIGHT KG"
      unit_of_measurement: 'kg'
      value_template: >-
        {{ states("input_number.ben_weight_kg") }}
    ben_impedance:
      friendly_name: "BEN IMPEDANCE"
      unit_of_measurement: 'ohm'
      value_template: >-
        {{ states("input_number.ben_impedance") }}
```

```
bodymiscale:
  ben:
    sensors:
      weight: sensor.ben_weight_kg
      impedance: sensor.ben_impedance
    height: 165
    born: "1975-02-05"
    gender: "male"
    model_miscale: "181B"
```
