### ISSUE TITLE
Captured weight does not 'stick' and returns to unknown when ESPHome is updated

### ISSUE THREAD

**Issue by xbmcnut** [dckiller51/bodymiscale#31]
Hi there,

Thanks for the great add-on. I have this working with an ESPHome BLE scanner using the code below. While the weight comes in within a few seconds, if I update ESPHome on the BLE scanner (something that happens regularly), the captured weight reading is lost and the entities return a state of `unknown.` I believe this may also happen sometimes when I restart HA but I haven't categorically proven that yet.

Is there something I'm missing to make the data state in Home Assistant permanent?
```
sensor:
  - platform: xiaomi_miscale
    mac_address: 'xx:xxx:xx:xx:xx'
    weight:
      name: "Xiaomi Mi Scale Weight"
      id: weight_miscale
      on_value:
        then:
          - lambda: |-
              if (id(weight_miscale).state >= 67 && id(weight_miscale).state <= 80) {
                return id(weight_user1).publish_state(x);}
              else if (id(weight_miscale).state >= 45 && id(weight_miscale).state <= 65) {
                return id(weight_user2).publish_state(x);}

  - platform: template
    state_class: measurement
    name: Weight Pete
    id: weight_user1
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
    
  - platform: template
    state_class: measurement
    name: Weight Ali
    id: weight_user2
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
```

**Comment by dckiller51** [comment]
> Salut,
> 
> Merci pour le super add-on. Cela fonctionne avec un scanner ESPHome BLE en utilisant le code ci-dessous. Alors que le poids arrive en quelques secondes, si je mets à jour ESPHome sur le scanner BLE (quelque chose qui se produit régulièrement), la lecture du poids capturé est perdue et les entités renvoient un état de `unknown.`Je crois que cela peut aussi arriver parfois lorsque je redémarre HA mais Je ne l'ai pas encore prouvé catégoriquement.
> 
> Y a-t-il quelque chose qui me manque pour rendre l'état des données permanent dans Home Assistant ?
> 
> ```
> sensor:
>   - platform: xiaomi_miscale
>     mac_address: 'xx:xxx:xx:xx:xx'
>     weight:
>       name: "Xiaomi Mi Scale Weight"
>       id: weight_miscale
>       on_value:
>         then:
>           - lambda: |-
>               if (id(weight_miscale).state >= 67 && id(weight_miscale).state <= 80) {
>                 return id(weight_user1).publish_state(x);}
>               else if (id(weight_miscale).state >= 45 && id(weight_miscale).state <= 65) {
>                 return id(weight_user2).publish_state(x);}
> 
>   - platform: template
>     state_class: measurement
>     name: Weight Pete
>     id: weight_user1
>     unit_of_measurement: 'kg'
>     icon: mdi:weight-kilogram
>     accuracy_decimals: 2
>     
>   - platform: template
>     state_class: measurement
>     name: Weight Ali
>     id: weight_user2
>     unit_of_measurement: 'kg'
>     icon: mdi:weight-kilogram
>     accuracy_decimals: 2
> ```

Yes, I can confirm that after a restart the weight has been lost.
Look here for my workaround https://github.com/dckiller51/bodymiscale/issues/30#issuecomment-915569086

**Comment by xbmcnut** [comment]
Thanks, but is there a way to use mqtt.publish in the ESPHome config to publish the weight to a topic with retain enabled? That would be a good workaround.

Not so keen to install Node Red just for one entity.

**Comment by xbmcnut** [comment]
I've added an automation on the HA end to create a retained message I can use for a new 'sticky' sensor.
```
- alias: 'Publish weight values when scales change'
  trigger:
    platform: state
    entity_id: sensor.weight_pete, sensor.weight_ali
  action:
    service: mqtt.publish
    data_template:
      payload: "{{trigger.to_state.state}}"
      topic: "tele/scales/{{trigger.to_state.object_id}}" 
      retain: true
```
