### ISSUE TITLE
No attributes to sensor

### ISSUE THREAD

**Issue by twangraus** [dckiller51/bodymiscale#34]
Hey guys,

My HA server is to far away from my scale, so i have a ESP32 with ESPHome to get the data to HA. I get the weight and impedance for 2 users. Ive entered these sensors in the bodymiscale.yaml, but i dont get any attributes like BMI, Bone mass etc. 

Is There something i have done wrong? Does the calculated data appear as attributes to the original sensors?
I have 4 sensor, 2 per user, both with weight and impedance. My bodymiscale.yaml is as follow:

```
twan:
  sensors:
    weight: sensor.weight_user1
    impedance: sensor.impedance_user1
  height: 185
  born: "xxxx-xx-xx"
  gender: "male"
  model_miscale: "181B"
  
jennifer:
  sensors:
    weight: sensor.weight_user2
    impedance: sensor.impedance_user2
  height: 175
  born: "xxxx-xx-xx"
  gender: "female"
  model_miscale: "181B"
```
