### ISSUE TITLE
V2.0.0 does not trigger correctly when sensors updated

### ISSUE THREAD

**Issue by borpin** [dckiller51/bodymiscale#65]
V2.0.0 does not work when the sensors are updated.

I have 2 x Scales defined and both updated when one set of sensors updated.

Node-Red did not pick up the state change so something is amiss.

Reverted to 1.1.5 and all OK.

**Comment by dckiller51** [comment]
hello, @edenhaus is working on a update that should bring some corrections.

**Comment by edenhaus** [comment]
Can you please describe your setup with Node Red.
Is the sensor (`bodymiscale.YOURNAME`) in HA updated correctly with v2?

**Comment by borpin** [comment]
All Node-RED is doing is waiting for the bodymiscale entity state  to change (update).

![image](https://user-images.githubusercontent.com/1322749/159158455-3a332fc3-098b-4b4b-993b-727ade486d3b.png)

entity state - Last Changed date is the first time it ran having reverted to V1.1.5, Last Updated was the reading this morning.

![image](https://user-images.githubusercontent.com/1322749/159158536-42b82ea4-ed44-4a61-9d2c-df88190922c6.png)

> Is the sensor (`bodymiscale.YOURNAME`) in HA updated correctly with v2?

Seems to have as it doesn't work once updated.

As I said, I have 2 people defined (so 2 entities) and both entities get updated at the same time (i.e. when one set of weight/impedance sensors update) on V2.0 even though the 2 bodymiscale entities are linked to different sensors.

**Comment by edenhaus** [comment]
I will verify it by the end of this week (Currently I'm on holiday).

> As I said, I have 2 people defined (so 2 entities) and both entities get updated at the same time (i.e. when one set of weight/impedance sensors update) on V2.0 even though the 2 bodymiscale entities are linked to different sensors.

Can you please share your config as I don't understand how both entities can be updated the same time with different sensors (scales) configured

**Comment by borpin** [comment]
> Can you please share your config as I don't understand how both entities can be updated the same time with different sensors (scales) configured

No neither do I - it shouldn't - only happens with V2!!!

```
scale_brian:
  sensors:
    weight: sensor.weight_brian
    impedance: sensor.impedance_brian
  height: 182
  born: "xxxx-xx-xx"
  gender: "male"
  model_miscale: "181B"

scale_k:
  sensors:
    weight: sensor.weight_k
    impedance: sensor.impedance_k
  height: 163
  born: "xxxx-xx-xx"
  gender: "female"
  model_miscale: "181B"
```

Can you also check the new code fixes issue #51 at the same time. Needs to wait for both sensors to update before reporting else it seems to use the impedance from last time.

**Comment by edenhaus** [comment]
I cannot reproduce your issue.

The entity is updated correctly when one of it sensors get a new state and only the specific entity and not all bodymiscale entities.

I used the following config for testing:
```yaml
input_number:
  weight:
    name: Weight
    initial: 70
    min: 10
    max: 200
    step: 0.1
  impedance:
    name: Impedance
    initial: 400
    min: 0
    max: 3000
    step: 1
  weight2:
    name: Weight
    initial: 80
    min: 10
    max: 200
    step: 0.1
  impedance2:
    name: Impedance
    initial: 600
    min: 0
    max: 3000
    step: 1

bodymiscale:
  test:
    sensors:
      weight: input_number.weight
      impedance: input_number.impedance
    height: 180
    born: "1990-01-01"
    gender: "male"
    model_miscale: "181B"

  test2:
    sensors:
      weight: input_number.weight2
      impedance: input_number.impedance2
    height: 180
    born: "1990-01-01"
    gender: "male"
    model_miscale: "181B"
```
